version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234!
      MYSQL_DATABASE: foresthill
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234.
    ports:
      - "3306:3306"

